config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get 'tasks/new', to: 'tasks#new'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'task_edit'
  post '/tasks', to: 'tasks#create'
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy'
  get "tasks/:id", to: "tasks#find", as: :task


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def find
    @task = Task.find(params[:id])
  end

  def new
    # initialize a new instance to pass it to the new form
    @task = Task.new
  end

  def create
    task = Task.create(task_params)
    redirect_to task_path(task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    # find the restaurant
    # @restaurant = Restaurant.find(params[:id]) => set_restaurant before_action
    # update the restaurant's attributes
    @task = Task.find(params[:id])
    @task.update(task_params)
    # redirect to the restaurant show view
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    # redirecting to the index
    redirect_to tasks_path
  end

private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>Edit task</h2>

<%= form_for(@task) do |f| %>
  <div class="form"><%= f.label :title %>:
  <%= f.text_field :title %></div>
  <br/>
  <%= f.label :details %>:
  <%= f.text_field :details %>
  <br/>

 <%= f.submit %>
<% end %>

app/views/tasks/find.html.erb
<h1><%= @task.title %></h1>
<p><%= @task.details %></p>
<li><input type="checkbox"> This task is not completed yet</li>

<%= link_to('Return to list', tasks_path) %><br/>
<%= link_to('Edit task', task_edit_path) %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
<% @tasks.each do |task| %>
<li><input type="checkbox"> <%= link_to(task[:title], task_path(task)) %>
<%= link_to('🗑️', task_path(task), method: :delete, data: {confirm:"Are you sure you want to delete '#{task[:title]}'?"}) %></li>
<% end %>
<%= link_to('+ Add new task', 'tasks/new') %>

app/views/tasks/new.html.erb
<h2>Add new task</h2>

<%= form_for(@task) do |f| %>
  <div class="form"><%= f.label :title %>:
  <%= f.text_field :title %></div>
  <br/>
  <%= f.label :details %>:
  <%= f.text_field :details %>
  <br/>

 <%= f.submit %>
<% end %>